name: Build and Publish to npm

on:
    release:
        types: [published]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2.3.1
            - name: install and build
              run: |
                  npm i -g pnpm
                  pnpm i
                  pnpm run build
            - name: publish
              run: pnpm publish --no-git-checks --access public
