name: Build and Publish to npm

on:
    release:
        types: [published]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
            - name: Install and Build 🔧
              run: |
                  npm i -g pnpm
                  pnpm i
                  pnpm run build
            - run: pnpm publish --no-git-checks --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
