nname: Publish to npm

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
    steps:
        - name: Checkout 🛎️
          uses: actions/checkout@v1
        - name: Install and Build 🔧
          run: |
              npm i -g pnpm
              pnpm i
              pnpm run build
        - run: pnpm publish --access public
          env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
